<script src="<%= request.getContextPath() %>/template/js/jquery.min.js"></script>
<script src="<%= request.getContextPath() %>/template/js/jquery-3.0.0.min.js"></script>
<script src="<%= request.getContextPath() %>/template/js/bootstrap.min.js"></script>
<script src="<%= request.getContextPath() %>/template/js/bootstrap.bundle.min.js"></script>
<script src="<%= request.getContextPath() %>/template/js/bootstrap.js"></script>
<script src="<%= request.getContextPath() %>/template/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="<%= request.getContextPath() %>/template/js/owl.carousel.js"></script>
<script src="<%= request.getContextPath() %>/template/js/owl.carousel.min.js"></script>
<script src="<%= request.getContextPath() %>/template/js/custom.js"></script>